package com.chatgpt.ai.response;

import com.chatgpt.ai.ChatCompletionMessage;

/**
 * A completion generated by GPT-4
 *
 * https://beta.openai.com/docs/api-reference/completions/create
 */
public class ChatCompletionChoice {
    /**
     * The generated message.
     */
    private ChatCompletionMessage message;

    /**
     * This index of this completion in the returned list.
     */
    private Integer index;

    /**
     * The reason why GPT-4 stopped generating, for example "length".
     */
    private String finish_reason;

    public ChatCompletionMessage getMessage() {
        return message;
    }

    public void setMessage(ChatCompletionMessage message) {
        this.message = message;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public String getFinish_reason() {
        return finish_reason;
    }

    public void setFinish_reason(String finish_reason) {
        this.finish_reason = finish_reason;
    }
}
